sudo: required
services:
  - docker

before_install:
  - docker build -t 123saketh/docker-react -f Dockerfile.dev .

script:
  - docker run 123saketh/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react01"
  env: "Dockerreact01-env"
  bucket_name: "elasticbeanstalk-us-east-2-883847302082"
  bucket_path: "docker-react01"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



